export const DEBT_PATH_PREFIX = '/debts';

export const DEFAULT_LIMIT_RESPONSE_SIZE = 30;
export const DEFAULT_PAGE_SKIP = 1;


export const DEBTS_SORT_VALUES = {
    VALUE_ASC: "VALUE_ASC",
    VALUE_DESC: "VALUE_DESC",
    DEBT_DATE_ASC: "DEBT_DATE_ASC",
    DEBT_DATE_DESC: "DEBT_DATE_DESC"
}

export const SORT_DEBTS_REGEX = /^(VALUE_ASC|VALUE_DESC|DEBT_DATE_ASC|DEBT_DATE_DESC)$/;

